---
title: "02_data_processing"
format: html
---

```{r}

suppressPackageStartupMessages({
library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyverse)
library(harmony)
library(tidyr)
library(multtest)
library(metap)
library(tibble)
library(Matrix)
})
```

## Load and combine sample data

```{r}


#sample_path <- "/home/projects/exam_2026_22102/group2/intestine_data/sample_seurats/"

#reading the seruat objects
# B006 <- readRDS(str_c(sample_path, "B006_seurat.rds"))
# B008 <- readRDS(str_c(sample_path, "B008_seurat.rds"))
# B010 <- readRDS(str_c(sample_path, "B010_seurat.rds"))
# B011 <- readRDS(str_c(sample_path, "B011_seurat.rds"))
# B012 <- readRDS(str_c(sample_path, "B012_seurat.rds"))


# Adding meta data of each donor to thei seurat object
# B006$donor <- "B006"
# B008$donor <- "B008"
# B010$donor <- "B010"
# B011$donor <- "B011"
# B012$donor <- "B012"


# EC <- merge(
#   x = B006,
#   y = list(B008, B010, B011, B012),
#   add.cell.ids = c("B006","B008","B010","B011", "B012"),
#   project = "AllDonors"
# )
# 
# 
# # checking if meta data was perserved
# table(EC$donor)
# 
# # Joing layers so count matrix and such is pooled
# EC <- JoinLayers(EC)
# 
# # Saving the seurat 
# saveRDS(EC, file = "/home/projects/exam_2026_22102/group2/intestine_data/sample_seurats/EC_merged_seurat.rds")
# 
# dim(EC) # dim before subsetting, 545083 3569104

```

## Loading merged seurat

```{r}

EC <- readRDS('/home/projects/exam_2026_22102/group2/intestine_data/sample_seurats/EC_merged_seurat.rds')
```

Removing spatial information:

```{r}
# saving counts
counts <- GetAssayData(EC, layer= 'counts')

#Saving spatial 
spatial_genes <-  rownames(EC)[grepl(":", rownames(EC))]

#adding spatial genes:
#EC <- EC[spatial_genes, ] 

#Remving spatial information
keep_genes <- rownames(EC)[!grepl(":", rownames(EC))]

# Subset the Seurat object
EC <- EC[keep_genes, ] 
```

# QC of the data

## Percentages of mito and ribosomal

```{r}
#Mitochondrial genes
EC@meta.data[["percent.mt"]] <- PercentageFeatureSet(EC, pattern = "^MT-")

#Ribosomal genes proportions
EC[["percent.ribo"]] <- PercentageFeatureSet(EC, pattern = "^RPS|^RPL|^rps|^rpl")

```

Converting NA to 0:

```{r}
features <- c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo")

for (f in features) {
  if (f %in% colnames(EC@meta.data)) {          # check it exists
    x <- EC@meta.data[, f]                       # extract as vector
    x[is.na(x) | is.infinite(x)] <- 0            # replace NA/Inf with 0
    EC@meta.data[, f] <- x                        # write back
  } else {
    warning(paste("Feature not found in metadata:", f))
  }
}
```

Checking for no Na values for QC metric

```{r}
colSums(is.na(EC@meta.data[, c(
  "nFeature_RNA",
  "nCount_RNA",
  "percent.mt",
  "percent.ribo"
)]))
```

Making QC metric

```{r}

# making identity same for all
Idents(EC) <- factor(rep("all-cells", ncol(EC)))
levels(Idents(EC))

# Restoring the identity: 
# Idents(EC) <- EC$donor

# Visualize QC metrics as a violin plot
p <- VlnPlot(EC, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo"), ncol = 4, group.by = NULL)
p
```

## Doublets investigation

```{r}

```

# Random subsetting data

```{r}

set.seed(123) # seed for reproducibility

cells.use <- unlist(
  lapply(
    split(Cells(EC), EC$donor),
    function(x) sample(x, 8000)
  )
)

EC <- subset(EC, cells = cells.use)

dim(EC) # dim subsetting

```

# Normalization, variables features and scaling

```{r}

```

# Saving final seurat object

```{r}

#saveRDS(EC, file = "/home/projects/exam_2026_22102/group2/intestine_data/sample_seurats/EC_preproccessed_seurat.rds")


```
