---
title: "05_cell_cell_communication"
format: html
---

```{r}
# Load libraries
suppressPackageStartupMessages({
library(CellChat)
library(patchwork)
library(future)
})
options(stringsAsFactors = FALSE)

source("paths.R")

EC <- readRDS(paste0(EC_seurats_path, "04_EC.rds"))
```

Investigating cell-cell communication can be a good initial analysis to gain insight into the [potential]{.underline} interactions that the cells might have with each other.

This analysis requires a receptor-ligand database that we obtain with CellChat

```{r}
# Load databatse
CellChatDB <- CellChatDB.human
showDatabaseCategory(CellChatDB)
```

```{r}
EC$samples <- EC$donor
# Create a CellChat object
cellchat <- createCellChat(object = EC, 
                           meta = EC@meta.data,
                           group.by = "cell_type_automatic")
```

```{r}
# Subset the database to 'Secreted Signaling'
CellChatDB.ss <- subsetDB(CellChatDB, 
                          search = "Secreted Signaling")

cellchat@DB <- CellChatDB.ss
```

```{r}
# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
```

```{r}
# Set parallel to split the tasks
future::plan("multisession", workers = 4)
```

```{r}
# Compute the communication probability and infer cellular communication network
# TriMean: Calculate the average gene expression per cell group
options(future.globals.maxSize = 4 * 1024^3)
# Increase the maximum size (e.g. 4 GB)

ptm = Sys.time()
cellchat <- computeCommunProb(cellchat, 
                              type = "triMean")
```

```{r}
# Calculate the cell-cell communication network
cellchat <- computeCommunProb(cellchat)
```

```{r}
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat <- filterCommunication(cellchat, 
                                min.cells = 10)

# Extract the inferred cellular communication network as a data frame
df.net <- subsetCommunication(cellchat)  

# Infer the cell-cell communication at a signaling pathway level
cellchat <- computeCommunProbPathway(cellchat)
```

```{r}
# Set the workload back to sequential
future::plan(sequential)
```

```{r}
#Calculate the aggregated cell-cell communication network
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
# Visualize
par(mfrow = c(1,2), xpd=TRUE, mar=c(4,4,4,4)) # enlarge right margin 
netVisual_circle(cellchat@net$count, 
                 vertex.weight = groupSize, 
                 weight.scale = TRUE, 
                 label.edge=FALSE, 
                 title.name = "Number of interactions") 
netVisual_circle(cellchat@net$weight, 
                 vertex.weight = groupSize, 
                 weight.scale = TRUE, 
                 label.edge=FALSE, 
                 title.name = "Interaction strength")
```

```{r}
pathways <- cellchat@netP$pathways

pathways.show <- c("ANGPTL")

# Circle plot
par(mfrow = c(1,1), xpd=TRUE, mar=c(4,4,4,4))
netVisual_aggregate(cellchat, 
                    signaling = pathways.show, 
                    layout = "circle")
```
